name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r req.txt

      - name: Run migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: Build Docker image (optional)
        run: docker build -t myapp .

      - name: Run Django app in Docker (optional)
        run: |
          docker run -d -p 8000:8000 --name web myapp
          sleep 10

      - name: Check if server is up (optional)
        run: |
          curl --fail http://localhost:8000 || exit 1
